server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_manager_db
    username: postgres
    password: root
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect